### ISSUE TITLE
How about an empty String there? :-)

### ISSUE THREAD

**Issue by LIttleAncientForestKami** [kukulam/module_testing#2]
https://github.com/kukulam/module_testing/blob/ca56c2614c177fe33586384cdb7781fb29627220/src/main/java/kukulam/module/testing/level/C/StringHandler.java#L29

**Comment by kukulam** [comment]
Thanks for suggestion ! applied in [commit](https://github.com/kukulam/module_testing/commit/9a6e0f05a8acc6272b8ee2b23010a3d7505d5e88) 💪 😄
